// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPyjLsihfAHRHcW2e7pyjxlN-nOwyRmg',
    appId: '1:308202335394:android:30fa6883d96e8501927bfb',
    messagingSenderId: '308202335394',
    projectId: 'welltaxi-f2734',
    databaseURL: 'https://welltaxi-f2734-default-rtdb.firebaseio.com',
    storageBucket: 'welltaxi-f2734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYXgKIoAMK6hdS7EYAFU5sySg9xwNWHg',
    appId: '1:308202335394:ios:06be6cc0029398ad927bfb',
    messagingSenderId: '308202335394',
    projectId: 'welltaxi-f2734',
    databaseURL: 'https://welltaxi-f2734-default-rtdb.firebaseio.com',
    storageBucket: 'welltaxi-f2734.appspot.com',
    iosClientId: '308202335394-p4j1qk5knl99o8pgebs69do0hlm0dghb.apps.googleusercontent.com',
    iosBundleId: 'br.com.wellysonpontes.carRider',
  );
}
